### ISSUE TITLE
Please add repository for brew tap

### ISSUE THREAD

**Issue by joergschiller** [ferkulat/csv2xls#12]
Hi,

thanks for your work, I've successfully converted a few csv files easily on the command-line with your utility. But it took me a few more minutes to install it on my mac.

I've created an example repository for use with `brew tap` and fixed the formula to run on the newest version of Homebrew. I guess it would be helpful for others to install csv2xls with a new repo ferkulat/homebrew-csv2xls.

```
brew tap ferkulat/csv2xls
brew install csv2xls
```

So please feel free to copy it from https://github.com/joergschiller/homebrew-csv2xls. For `brew tap` you need to name it homebrew-csv2xls but on the command-line one can install it with `brew tap ferkulat/csv2xls`.

For more information see: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/brew-tap.md.

Kind regards,
Joerg

**Comment by ferkulat** [comment]
Hello Joerg,
thank you for this request.

Sorry for this late answer.
Initially I added a branch named "package".
Could you make your changes on this branch and make a pull request?

In general I am not sure anymore, if putting package files in the same repository is the right way.
If one would put it in its own repository, how about keeping your repository just to hold the bew package?

I am open for suggestions.

with kind regards

Marcel
