### ISSUE TITLE
Can not find configure file for installation.

### ISSUE THREAD

**Issue by SopalajodeArrierez** [ferkulat/csv2xls#13]
Excuse me, but where is the "configure" file to enter "./configure" prior to "make install"?

**Comment by ferkulat** [comment]
Hello SopalajodeArrierez,
you are right, some time ago I removed auto generated files from repo.
At first you will have to call the script "bootstrap.sh". This will create the scripts "configure" and "Makefile".
I will have to update the documentation about this.

Thank you for reporting this issue.

**Comment by SopalajodeArrierez** [comment]
Con fecha jueves, 09 de marzo de 2017, 8:40:41 pm, escribiste:


Hello SopalajodeArrierez,
you are right, some time ago I removed auto generated files from repo.
At first you will have to call the script "bootstrap.sh". This will create the scripts "configure" and "Makefile".
I will have to update the documentation about this.
Thank you for reporting this issue.

	All right.
	Thanks to you for answering.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

  

========================
Luis Rivas - alias Sopalajo de Arriérez y Torrezno
Libertario Internauta

**Comment by ferkulat** [comment]
fixed with 134f1d859550b29f0ebcb801fab35fdf4a06e6cd
