### ISSUE TITLE
UTF8 characters

### ISSUE THREAD

**Issue by andrikom** [ferkulat/csv2xls#6]
Hi All,

I have got a problem with converting UTF8 characters in the source CSV file to XLS.

Characters: Á,É,Ó,Ő,Ű,... etc.

Currently I can see "manuбl" instead of "manuál", or "festйs" instead of "festés" in the converted excel cells.

(It is also appreciated to convert to "manual" or "festes".)

Please let me know how is that possible to convert these characters without any change in the texts or to convert to A,E,O,U... etc.

Thanks & Regards,

Miklos

**Note:

manual = manual
festes = painting

**Comment by heinerbremer** [comment]
Hi Ferkulat!

I followed the wiki and tried several times - but I just can't get the file to compile. It always throws up some other errors. As I don't understand anything concerning compiling I kindly ask you if it would be possible to provide the pre-compiled version of csv2xls that has UTF-support.

Thanks in advance for your help and this great tool!

Regards, Heiner.

**Comment by ferkulat** [comment]
Hello Heiner, 
are you talking about a precompiled linux binary?

**Comment by heinerbremer** [comment]
Ah, sorry! Should have mentioned that I'm using Windows.

**Comment by ferkulat** [comment]
Hello Heiner, 
have you tried https://github.com/ferkulat/csv2xls/releases ?
Since I built it a while ago, I am not shure, but I thought it was built with utf8 support in it.

**Comment by heinerbremer** [comment]
Yes, I'm using the file csv2xls-0.3.5-win32-precompiled.zip - but unfortunately each cell with an umlaut (ä, ö, ü) is "converted" as "iconv failed!".

**Comment by ferkulat** [comment]
OK,
I am going to fix it.
I can not promise, but soon I will find some time.

**Comment by heinerbremer** [comment]
Great! Thanks a lot!

**Comment by ferkulat** [comment]
Hello Heiner,

I just tested the precompiled from releases.
It converts utf8 correctly.

Are you sure your input file has utf8 encoding and not some ISO-XXXXX?
Could you please attatch the file in question in here?
I hope this is a really small sample file :)

**Comment by heinerbremer** [comment]
OMG! This is so embarassing... the input was indeed not UTF8 encoded. Just tried it with a different file and it worked like it's supposed to. Sorry for the confusion and inconvenience! (And a big THANK YOU for your help!)

**Comment by ferkulat** [comment]
You are welcome :)
